### ISSUE TITLE
queryOr don't behaves like I expected

### ISSUE THREAD

**Issue by LawnCable** [luggage66/Sprache-js#2]
I expected `queryOr` to try the all parsers on the same input and take the first one that succeeds.
But instead it calls the next parser with the remainder of the previous failed one:
```js
const { Parse } = require('sprache');

const Integer = Parse.digit.many().select(digits => {
    return Number.parseInt(digits.join(''), 10);
}).token().named('an integer');

const SignedInteger = Parse.query(function* () {
    const sign = yield Parse.char(input => /\+|-/.test(input), "+ or - sign")
    const number = yield Integer;
    return Parse.return((sign && sign == '-') ? -number : number)
})

const SignedIntegerWithL = Parse.query(function* () {
    const number = yield SignedInteger;
    const last = yield Parse.char('L').once();
    return Parse.return("number");
})

const NumberParser = Parse.queryOr(function* () {
    yield SignedIntegerWithL;
    yield SignedInteger;
})
try {
    console.log(NumberParser.parse("+5324")) // return an error
} catch (error) { console.log(error)}

console.log(NumberParser.parse("-5324+88")) // returns 88
console.log(NumberParser.parse("-5324-9")) // returns -9
```
If I remove that line it works as I expected: https://github.com/luggage66/Sprache-js/blob/1086ba713ff80dfcd0d8b0eed3433b333845802c/src/parse.ts#L475

**Comment by luggage66** [comment]
Hm. I'll look at this in a couple hours.

**Comment by luggage66** [comment]
It's fixed. That line you pointed out needed moved, not removed entirely. I also updated all dependences, so re-install npm packages if you have the project checked out.

The `Parse.query()`, like you use in IntegerWithL, consumes the input even on failure. This is different than other Parsers. They only consume on success. The original Sprache seems to work that way, too, since I copied the tests from it. The `queryOr()` is no longer broken by that behavior due to the change you pointed out.
